language: 
 - python

python: 
 - 3.6

install:
 - pip install --upgrade pip
 - pip install -r requirements.txt

script:
 - cd code
 - python main.py --genFaceCrops --frames 1 --videoDirectory ../test/Videos
 - cd ..   
 - pytest --flake8 
